language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm install -g gulp
script: 
  - npm run build
after_success:
  - npm run test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
